"use client";
import { useMemo, useState } from "react";

type Product={id:number;category:string;title:string;subtitle:string;price:number;originalPrice?:number;tag:string;symbol:string;description:string;includes:string[];recommended?:boolean};
const products:Product[]=[
{id:1,category:"핵심 풀이",title:"핵심 사주풀이",subtitle:"타고난 기질과 지금 필요한 운의 흐름",price:29000,tag:"입문 추천",symbol:"命",description:"타고난 기질과 지금 나에게 필요한 운의 흐름을 핵심만 선별해 담은 5페이지 분량의 사주풀이입니다.",includes:["타고난 핵심 기질","현재 운의 흐름","지금 필요한 선택 조언","약 5페이지 리포트"]},
{id:2,category:"심층 풀이",title:"심층 사주풀이",subtitle:"한 가지 고민을 깊이 있게 분석",price:39000,tag:"집중 분석",symbol:"深",description:"연애, 직업, 재물의 흐름과 선택 방향 중 한 가지 주제를 선택해 깊이 있게 분석하는 8~10페이지 분량의 심층 사주풀이입니다.",includes:["연애·직업·재물 중 1개 선택","선택 주제의 흐름 분석","시기와 선택 방향","약 8~10페이지 리포트"]},
{id:3,category:"자녀·양육",title:"자녀 기질 분석&양육 가이드",subtitle:"아이 기질에 맞춘 부모 소통법",price:45000,tag:"부모님 추천",symbol:"育",description:"아이의 타고난 기질과 부모의 소통법, 상황별 맞춤 양육 포인트를 담은 12페이지 분량의 실전 양육 가이드입니다.",includes:["아이의 핵심 기질 분석","부모·아이 소통법","맞춤 칭찬과 훈육 포인트","약 12페이지 가이드"]},
{id:4,category:"프리미엄",title:"운명설계 프리미엄",subtitle:"인생의 큰 흐름과 선택의 시기를 한눈에",price:59000,tag:"PREMIUM",symbol:"運",description:"인생의 큰 흐름과 중요한 선택의 시기를 종합적으로 설계하는 30페이지 분량의 프리미엄 종합 사주입니다.",includes:["타고난 기질과 인생 흐름","직업·재물·관계 종합 분석","중요한 선택과 변화의 시기","약 30페이지 프리미엄 리포트"],recommended:true}];
const money=(v:number)=>`${v.toLocaleString("ko-KR")}원`;
const formatPhone=(value:string)=>{const digits=value.replace(/\D/g,"").slice(0,11);if(digits.length<=3)return digits;if(digits.length<=7)return `${digits.slice(0,3)}-${digits.slice(3)}`;return `${digits.slice(0,3)}-${digits.slice(3,7)}-${digits.slice(7)}`};
const consultationLinks={
 kakao:"https://open.kakao.com/o/sVmybTAi",
 daangn:"https://www.daangn.com/kr/local-profile/ouk4visj8p1v/?referrer=share",
 channels:"https://linkbio.co/8062310NRlU7R?utm_source=threads&utm_medium=social&utm_content=link_in_bio"
};
const consultationSheetUrl="https://script.google.com/macros/s/AKfycbydZo8zQ-V7dF_zzF27sieHzLMbCcONVHKdAZN6AArZDGpIejr1s_dkqdpGmf966M-j/exec";
type TemperamentType="warm"|"steady"|"leading";
const quizQuestions=[
 {question:"낯선 장소나 사람을 만났을 때 아이는 어떤가요?",options:[{text:"먼저 다가가며 금방 어울려요",type:"leading" as TemperamentType},{text:"주변을 살핀 뒤 천천히 다가가요",type:"steady" as TemperamentType},{text:"부모 곁에서 마음이 놓일 때까지 기다려요",type:"warm" as TemperamentType}]},
 {question:"원하는 일이 뜻대로 되지 않을 때 주로 어떻게 반응하나요?",options:[{text:"왜 안 되는지 계속 묻거나 강하게 주장해요",type:"leading" as TemperamentType},{text:"표현은 적지만 한동안 마음에 담아둬요",type:"steady" as TemperamentType},{text:"속상한 감정을 바로 표현하고 위로를 원해요",type:"warm" as TemperamentType}]},
 {question:"새로운 활동을 시작할 때 가장 가까운 모습은 무엇인가요?",options:[{text:"일단 해보며 자기 방식대로 이끌어요",type:"leading" as TemperamentType},{text:"충분히 보고 익숙해진 뒤 시작해요",type:"steady" as TemperamentType},{text:"함께 해준다는 확신이 있어야 시작해요",type:"warm" as TemperamentType}]},
 {question:"칭찬을 받았을 때 아이의 반응은 어떤가요?",options:[{text:"더 잘하고 싶어 하며 다음 목표를 찾아요",type:"leading" as TemperamentType},{text:"겉으로는 담담하지만 같은 행동을 꾸준히 해요",type:"steady" as TemperamentType},{text:"표정이 밝아지고 칭찬한 사람과 더 가까워져요",type:"warm" as TemperamentType}]},
 {question:"부모의 말을 가장 잘 받아들이는 순간은 언제인가요?",options:[{text:"해야 할 기준과 이유를 분명히 알려줄 때",type:"leading" as TemperamentType},{text:"생각할 시간을 주고 차분히 기다려줄 때",type:"steady" as TemperamentType},{text:"마음을 먼저 알아주고 다정하게 말할 때",type:"warm" as TemperamentType}]}
];
const quizResults:Record<TemperamentType,{symbol:string;title:string;summary:string;tips:string[]}>=
 {warm:{symbol:"溫",title:"마음 연결형",summary:"감정의 교감과 따뜻한 반응 속에서 안정감을 얻는 아이예요.",tips:["마음을 먼저 말로 알아주세요","결과보다 과정과 마음을 칭찬해 주세요","부모와 연결되어 있다는 확신을 주세요"]},steady:{symbol:"穩",title:"신중 관찰형",summary:"충분히 살피고 자기 속도로 익숙해질 때 편안해지는 아이예요.",tips:["대답과 행동을 재촉하지 말아주세요","새로운 일은 미리 설명해 주세요","작은 변화부터 천천히 경험하게 해주세요"]},leading:{symbol:"進",title:"주도 개척형",summary:"스스로 선택하고 시도할 때 에너지가 살아나는 아이예요.",tips:["가능한 범위 안에서 선택권을 주세요","안 되는 일은 기준과 이유를 분명히 말해주세요","도전하는 태도와 노력을 구체적으로 인정해주세요"]}};

export default function Home(){
 const[category,setCategory]=useState("전체"),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<Product[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[ordered,setOrdered]=useState(false),[paying,setPaying]=useState(false),[paymentError,setPaymentError]=useState("");
 const[customer,setCustomer]=useState({name:"",phone:"",email:""});
 const[intake,setIntake]=useState({name:"",birthDate:"",birthTime:"",gender:"",phone:"",product:"자녀 기질 분석&양육 가이드",message:"",privacy:false});
 const[intakeStatus,setIntakeStatus]=useState<"idle"|"submitting"|"success"|"error">("idle");
 const[quizStep,setQuizStep]=useState(0),[quizAnswers,setQuizAnswers]=useState<TemperamentType[]>([]),[quizResult,setQuizResult]=useState<TemperamentType|null>(null);
 const visible=category==="전체"?products:products.filter(p=>p.category===category); const total=useMemo(()=>cart.reduce((s,i)=>s+i.price,0),[cart]);
 const addCart=(p:Product)=>{if(!cart.some(i=>i.id===p.id))setCart([...cart,p]);setSelected(null);setCartOpen(true)};
 const answerQuiz=(type:TemperamentType)=>{const next=[...quizAnswers,type];if(quizStep<quizQuestions.length-1){setQuizAnswers(next);setQuizStep(quizStep+1);return}const scores:Record<TemperamentType,number>={warm:0,steady:0,leading:0};next.forEach(answer=>scores[answer]++);setQuizAnswers(next);setQuizResult((Object.keys(scores) as TemperamentType[]).sort((a,b)=>scores[b]-scores[a])[0])};
 const resetQuiz=()=>{setQuizStep(0);setQuizAnswers([]);setQuizResult(null)};
 const submitIntake=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fields=Array.from(e.currentTarget.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>("input,select,textarea"));const payload={name:fields[0].value,gender:fields[1].value,birthDate:fields[2].value,birthTime:fields[3].value,phone:formatPhone(fields[4].value),product:fields[5].value,message:fields[6].value};setIntakeStatus("submitting");try{await fetch(consultationSheetUrl,{method:"POST",mode:"no-cors",headers:{"content-type":"text/plain;charset=UTF-8"},body:JSON.stringify(payload)});setIntakeStatus("success");setIntake({...intake,name:"",birthDate:"",birthTime:"",gender:"",phone:"",message:"",privacy:false})}catch{setIntakeStatus("error")}};
 const pay=async()=>{setPaying(true);setPaymentError("");try{const prepare=await fetch("/api/payments/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productIds:cart.map(i=>i.id),customer})});const ready=await prepare.json();if(!prepare.ok)throw new Error(ready.message);const confirm=await fetch("/api/payments/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentKey:ready.paymentKey,orderId:ready.orderId,amount:ready.amount})});const paid=await confirm.json();if(!confirm.ok||paid.status!=="PAID")throw new Error(paid.message??"결제가 완료되지 않았습니다.");setOrdered(true)}catch(error){setPaymentError(error instanceof Error?error.message:"결제 중 오류가 발생했습니다.")}finally{setPaying(false)}};
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">書</span><span>사주서가</span></a><nav><a href="#quiz">무료 기질 체크</a><a href="#consult">빠른 상담</a><a href="#products">사주 상품</a><a href="#process">이용 안내</a></nav><div className="header-actions"><a className="header-consult" href="#quiz">기질 체크</a><button className="cart-button" onClick={()=>setCartOpen(true)}>장바구니 <span>{cart.length}</span></button></div></header>
  <section className="hero" id="top"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-copy"><p className="eyebrow">CHILD TEMPERAMENT & PARENTING GUIDE</p><h1>아이의 마음이<br/><em>보이기 시작하는 순간</em></h1><p className="hero-desc">같은 말에도 다르게 반응하는 이유, 타고난 기질에서 실마리를 찾아보세요. 우리 아이에게 맞는 칭찬과 기다림, 기준을 세우는 방법을 섬세하게 안내합니다.</p><div className="hero-actions"><a className="primary" href="#consult">우리 아이 기질 상담하기</a><a className="text-link" href="#child-guide">양육 가이드 보기 →</a></div><div className="trust"><span><b>기질</b>을 이해하고</span><i/><span><b>소통법</b>을 찾고</span><i/><span><b>양육 기준</b>을 세워요</span></div></div><div className="hero-seal child-seal"><span>아이의 기질</span><strong>育</strong><small>마음을 읽는 양육</small></div></section>
  <section className="temperament-section" aria-labelledby="temperament-title"><div className="temperament-heading"><p className="section-label">UNDERSTAND YOUR CHILD</p><h2 id="temperament-title">아이마다 마음을 여는 방식은 다릅니다</h2><p>타고난 기질을 알면, 지금 우리 아이에게 필요한 부모의 말과 태도가 조금 더 선명해집니다.</p></div><div className="temperament-grid"><article><span>01</span><h3>칭찬할수록<br/>자라는 아이</h3><p>어떤 인정과 표현이 아이의 자신감을 키우는지 살펴봅니다.</p></article><article><span>02</span><h3>기다려줄수록<br/>마음을 여는 아이</h3><p>재촉보다 시간이 필요한 순간과 편안한 대화법을 찾습니다.</p></article><article><span>03</span><h3>분명한 기준에서<br/>안정되는 아이</h3><p>혼내지 않고도 경계와 약속을 전하는 방법을 안내합니다.</p></article></div><div className="temperament-cta"><p><b>생년월일시</b>를 준비해 주세요. 아이의 기질과 맞춤 소통법을 함께 살펴드릴게요.</p><a href="#consult">상담 채널 선택하기 →</a></div></section>
  <section className="quiz-section" id="quiz"><div className="quiz-intro"><p className="section-label">FREE TEMPERAMENT CHECK</p><span className="quiz-badge">약 1분 · 무료</span><h2>우리 아이는 어떤 방식으로<br/>마음을 열까요?</h2><p>평소 아이와 가장 가까운 모습을 선택해 주세요.<br/>5가지 질문으로 간단한 기질 경향과 소통 팁을 알려드려요.</p><div className="quiz-points"><span>✓ 별도 가입 없음</span><span>✓ 개인정보 입력 없음</span><span>✓ 즉시 결과 확인</span></div></div><div className="quiz-card" aria-live="polite">{!quizResult?<><div className="quiz-progress"><div><span>질문 {quizStep+1}</span><b>{quizQuestions.length}</b></div><i style={{width:`${((quizStep+1)/quizQuestions.length)*100}%`}}/></div><p className="quiz-question">{quizQuestions[quizStep].question}</p><div className="quiz-options">{quizQuestions[quizStep].options.map((option,index)=><button key={option.text} onClick={()=>answerQuiz(option.type)}><span>{String.fromCharCode(65+index)}</span>{option.text}<b>→</b></button>)}</div><small>정답은 없어요. 가장 자주 보이는 모습을 골라주세요.</small></>:<div className="quiz-result"><p className="result-label">간단 기질 체크 결과</p><div className="result-symbol">{quizResults[quizResult].symbol}</div><h3>{quizResults[quizResult].title}</h3><p>{quizResults[quizResult].summary}</p><ul>{quizResults[quizResult].tips.map(tip=><li key={tip}>✓ {tip}</li>)}</ul><div className="result-notice">이 결과는 간단한 경향 확인용이에요. 생년월일시를 함께 보면 아이의 기질과 소통법을 더 구체적으로 살펴볼 수 있습니다.</div><a className="primary result-cta" href="#consult">정확한 분석 받아보기</a><button className="quiz-reset" onClick={resetQuiz}>다시 체크하기</button></div>}</div></section>
  <section className="intake-section" id="consult"><div className="intake-copy"><p className="section-label">PERSONAL CONSULTATION</p><h2>생년월일시를 남기면<br/>상담 준비가 더 빨라져요</h2><p>아이 또는 상담 대상자의 기본 정보를 남겨주세요. 접수 내용을 확인한 뒤 연락드리겠습니다.</p><ul><li>✓ 입력 내용은 상담 준비에만 사용합니다.</li><li>✓ 태어난 시간을 모르면 ‘모름’을 선택해도 됩니다.</li><li>✓ 접수 후 익숙한 상담 채널에서 이어갈 수 있어요.</li></ul></div><form className="intake-form" onSubmit={submitIntake}><div className="form-grid"><label>이름<span>*</span><input required value={intake.name} onChange={e=>setIntake({...intake,name:e.target.value})} placeholder="상담 대상자 이름"/></label><label>성별<span>*</span><select required value={intake.gender} onChange={e=>setIntake({...intake,gender:e.target.value})}><option value="">선택해 주세요</option><option>여성</option><option>남성</option></select></label><label>생년월일<span>*</span><input required type="date" value={intake.birthDate} onChange={e=>setIntake({...intake,birthDate:e.target.value})}/></label><label>태어난 시간<span>*</span><input required value={intake.birthTime} onChange={e=>setIntake({...intake,birthTime:e.target.value})} placeholder="예: 오후 3:20 또는 모름"/></label><label>연락처<span>*</span><input required type="tel" inputMode="numeric" autoComplete="tel" maxLength={13} pattern="010-[0-9]{4}-[0-9]{4}" title="010-1234-5678 형식의 휴대폰 번호를 입력해 주세요." value={intake.phone} onChange={e=>setIntake({...intake,phone:formatPhone(e.target.value)})} placeholder="010-0000-0000"/></label><label>관심 상품<select value={intake.product} onChange={e=>setIntake({...intake,product:e.target.value})}>{products.map(p=><option key={p.id}>{p.title}</option>)}</select></label></div><label className="message-field">궁금한 내용<textarea rows={4} value={intake.message} onChange={e=>setIntake({...intake,message:e.target.value})} placeholder="아이의 반응이나 현재 고민을 간단히 적어주세요."/></label><label className="privacy-check"><input required type="checkbox" checked={intake.privacy} onChange={e=>setIntake({...intake,privacy:e.target.checked})}/><span>상담을 위한 개인정보 수집·이용에 동의합니다. <b>(필수)</b></span></label><button className="primary intake-submit" disabled={intakeStatus==="submitting"}>{intakeStatus==="submitting"?"접수 중...":"상담 정보 접수하기"}</button>{intakeStatus==="success"&&<p className="form-success">✓ 상담 정보가 접수되었습니다. 확인 후 연락드릴게요.</p>}{intakeStatus==="error"&&<p className="form-error">접수 중 문제가 발생했습니다. 잠시 후 다시 시도해주세요.</p>}</form></section>
  <section className="consult-section"><div className="consult-heading"><p className="section-label">QUICK CONSULTATION</p><h2>익숙한 채널에서<br/>편하게 상담을 시작하세요</h2><p>회원가입 없이 원하는 채널을 선택하면 바로 상담 화면으로 이동합니다.</p></div><div className="consult-grid"><a className="consult-card kakao" href={consultationLinks.kakao} target="_blank" rel="noopener noreferrer" aria-label="카카오톡으로 상담하기, 새 창 열림"><span className="channel-icon">K</span><div><small>빠른 문의에 추천</small><h3>카카오 상담</h3><p>오픈채팅으로 간편하게<br/>궁금한 내용을 남겨주세요.</p></div><b>바로 상담하기 <i>↗</i></b></a><a className="consult-card daangn" href={consultationLinks.daangn} target="_blank" rel="noopener noreferrer" aria-label="당근으로 상담하기, 새 창 열림"><span className="channel-icon">D</span><div><small>당근 이용자라면</small><h3>당근 상담</h3><p>사주서가 지역 프로필에서<br/>채팅으로 상담할 수 있어요.</p></div><b>프로필에서 상담하기 <i>↗</i></b></a><a className="consult-card instagram" href={consultationLinks.channels} target="_blank" rel="noopener noreferrer" aria-label="인스타그램과 전체 상담 채널 보기, 새 창 열림"><span className="channel-icon">@</span><div><small>소식과 상담을 한곳에서</small><h3>인스타·전체 채널</h3><p>콘텐츠를 둘러보고 원하는<br/>상담 채널을 선택해보세요.</p></div><b>모든 채널 보기 <i>↗</i></b></a></div><p className="consult-note"><span>✓</span> 상담 전 상품을 정하지 않아도 괜찮아요. 고민에 맞는 상품부터 안내해드릴게요.</p></section>
  <section className="intro" id="story"><p className="section-label">CURATED FOR YOU</p><h2>삶의 질문에 따라<br/>섬세하게 고른 사주 리포트</h2><p>단순한 풀이를 넘어, 지금의 나에게 필요한 이해와 방향을 전합니다.</p></section>
  <section className="products-section" id="products"><div className="filter-row">{["전체","핵심 풀이","심층 풀이","자녀·양육","프리미엄"].map(i=><button key={i} className={category===i?"active":""} onClick={()=>setCategory(i)}>{i}</button>)}</div><div className="product-grid">{visible.map(p=><article id={p.id===3?"child-guide":undefined} className={`product-card ${p.recommended?"featured":""} ${p.id===3?"child-product":""}`} key={p.id}><div className="product-art"><span className="product-tag">{p.tag}</span><b>{p.symbol}</b><small>{p.category}</small></div><div className="product-info"><p>{p.subtitle}</p><h3>{p.title}</h3><div className="price">{p.originalPrice&&<del>{money(p.originalPrice)}</del>}<strong>{money(p.price)}</strong></div><button onClick={()=>setSelected(p)}>상품 자세히 보기 <span>↗</span></button></div></article>)}</div></section>
  <section className="process" id="process"><div><p className="section-label">HOW IT WORKS</p><h2>당신만을 위한 해석이<br/>완성되는 과정</h2></div><ol>{[["01","상품 선택","지금 가장 궁금한 주제의 상품을 선택합니다."],["02","정보 입력","결제 후 생년월일시와 필요한 정보를 남겨주세요."],["03","개별 분석","전문 상담가가 사주 원국과 흐름을 직접 분석합니다."],["04","리포트 수령","3일 이내 깊이 있는 맞춤 리포트를 보내드립니다."]].map(x=><li key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></li>)}</ol></section>
  <section className="quote"><span>“</span><blockquote>운명은 정답이 아니라,<br/>나를 이해하는 하나의 언어입니다.</blockquote><p>사주서가는 당신이 스스로의 삶을 더 잘 선택하도록 돕습니다.</p></section>
  <footer><a className="brand inverse" href="#top"><span className="brand-mark">書</span><span>사주서가</span></a><p>삶의 흐름을 읽는 프리미엄 사주 큐레이션</p><div><a href="#consult">빠른 상담</a><a href="#products">상품 안내</a><a href="#process">이용 안내</a><a href="#story">브랜드 소개</a></div><small>© 2026 SAJUSEOGA. All rights reserved.</small></footer>
  <a className="floating-consult" href="#consult"><span>말풍선</span><b>빠른 상담</b></a>
  <div className="mobile-consult-bar" aria-label="빠른 상담 채널"><a href={consultationLinks.kakao} target="_blank" rel="noopener noreferrer"><span>K</span>카카오</a><a href={consultationLinks.daangn} target="_blank" rel="noopener noreferrer"><span>D</span>당근</a><a href={consultationLinks.channels} target="_blank" rel="noopener noreferrer"><span>@</span>전체 채널</a></div>
  {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><section className="modal detail-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="detail-symbol">{selected.symbol}</div><p className="section-label">{selected.category}</p><h2>{selected.title}</h2><p className="detail-copy">{selected.description}</p><h4>리포트 구성</h4><ul>{selected.includes.map(i=><li key={i}>✓ {i}</li>)}</ul><div className="modal-bottom"><strong>{money(selected.price)}</strong><button className="primary" onClick={()=>addCart(selected)}>장바구니 담기</button></div></section></div>}
  {cartOpen&&<div className="overlay drawer-overlay" onMouseDown={()=>setCartOpen(false)}><aside className="cart-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><h2>장바구니 <small>{cart.length}</small></h2><button className="close" onClick={()=>setCartOpen(false)}>×</button></div>{cart.length===0?<div className="empty"><b>담긴 상품이 없습니다.</b><p>지금 필요한 사주 리포트를 만나보세요.</p><button onClick={()=>setCartOpen(false)}>상품 둘러보기</button></div>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><span>{i.symbol}</span><div><small>{i.category}</small><b>{i.title}</b><strong>{money(i.price)}</strong></div><button onClick={()=>setCart(cart.filter(p=>p.id!==i.id))}>삭제</button></div>)}</div><div className="cart-total"><span>총 결제 금액</span><strong>{money(total)}</strong></div><button className="primary checkout-button" onClick={()=>{setCartOpen(false);setCheckout(true)}}>결제하기</button></>}</aside></div>}
  {checkout&&<div className="overlay"><section className="modal checkout-modal"><button className="close" onClick={()=>setCheckout(false)}>×</button>{ordered?<div className="complete"><div>✓</div><h2>주문이 완료되었습니다</h2><p>결제 확인 후 입력하신 연락처로<br/>상담 정보 입력 링크를 보내드릴게요.</p><button className="primary" onClick={()=>{setCheckout(false);setOrdered(false);setCart([]);setCustomer({name:"",phone:"",email:""})}}>확인</button></div>:<><p className="section-label">CHECKOUT</p><h2>주문·결제</h2><div className="order-summary">{cart.map(i=><div key={i.id}><span>{i.title}</span><b>{money(i.price)}</b></div>)}<div className="order-total"><span>결제 금액</span><strong>{money(total)}</strong></div></div><label>이름<input placeholder="주문자 이름" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>연락처<input placeholder="010-0000-0000" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>이메일<input placeholder="report@example.com" type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/></label><div className="pay-method"><button className="selected">신용카드</button><button>카카오페이</button><button>계좌이체</button></div>{paymentError&&<p className="payment-error">{paymentError}</p>}<button className="primary checkout-button" disabled={paying} onClick={pay}>{paying?"결제 처리 중...":`${money(total)} 결제하기`}</button><p className="demo-note">현재는 테스트 결제로 동작하며 실제 금액은 청구되지 않습니다.</p></>}</section></div>}
 </main>
}
