"use client";
import { useMemo, useState } from "react";

type Product={id:number;category:string;title:string;subtitle:string;price:number;originalPrice?:number;tag:string;symbol:string;description:string;includes:string[];recommended?:boolean};
const products:Product[]=[
{id:1,category:"개인 운세",title:"나를 읽는 사주",subtitle:"타고난 기질과 삶의 방향",price:29000,tag:"입문 추천",symbol:"命",description:"내 안의 강점과 반복되는 선택의 이유를 이해하는 가장 기본적인 사주 리포트입니다.",includes:["오행 균형 분석","타고난 성향과 강점","일·관계의 핵심 조언"]},
{id:2,category:"프리미엄",title:"2026 운세의 흐름",subtitle:"올해의 기회와 주의할 시기",price:49000,originalPrice:59000,tag:"BEST",symbol:"運",description:"올해의 큰 흐름부터 월별 변화까지, 중요한 선택의 타이밍을 세밀하게 짚어드립니다.",includes:["2026년 총운","월별 기회와 주의점","재물·직업·관계운"],recommended:true},
{id:3,category:"관계",title:"우리의 인연 궁합",subtitle:"두 사람의 관계 사용법",price:39000,tag:"2인 분석",symbol:"緣",description:"서로 다른 두 사람의 기질을 비교하고 더 편안하게 사랑하고 대화하는 방법을 안내합니다.",includes:["두 사람의 기질 비교","갈등과 소통 방식","관계의 장점과 보완점"]},
{id:4,category:"자녀·양육",title:"아이 기질 사용설명서",subtitle:"아이를 이해하는 맞춤 양육 가이드",price:39000,tag:"부모님 추천",symbol:"育",description:"아이의 타고난 기질에 맞춘 칭찬, 훈육, 소통 방법을 담은 부모님을 위한 안내서입니다.",includes:["아이의 핵심 기질","맞춤 칭찬·훈육법","부모와의 소통 가이드"]}];
const money=(v:number)=>`${v.toLocaleString("ko-KR")}원`;

export default function Home(){
 const[category,setCategory]=useState("전체"),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<Product[]>([]),[cartOpen,setCartOpen]=useState(false),[checkout,setCheckout]=useState(false),[ordered,setOrdered]=useState(false),[paying,setPaying]=useState(false),[paymentError,setPaymentError]=useState("");
 const[customer,setCustomer]=useState({name:"",phone:"",email:""});
 const visible=category==="전체"?products:products.filter(p=>p.category===category); const total=useMemo(()=>cart.reduce((s,i)=>s+i.price,0),[cart]);
 const addCart=(p:Product)=>{if(!cart.some(i=>i.id===p.id))setCart([...cart,p]);setSelected(null);setCartOpen(true)};
 const pay=async()=>{setPaying(true);setPaymentError("");try{const prepare=await fetch("/api/payments/prepare",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productIds:cart.map(i=>i.id),customer})});const ready=await prepare.json();if(!prepare.ok)throw new Error(ready.message);const confirm=await fetch("/api/payments/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({paymentKey:ready.paymentKey,orderId:ready.orderId,amount:ready.amount})});const paid=await confirm.json();if(!confirm.ok||paid.status!=="PAID")throw new Error(paid.message??"결제가 완료되지 않았습니다.");setOrdered(true)}catch(error){setPaymentError(error instanceof Error?error.message:"결제 중 오류가 발생했습니다.")}finally{setPaying(false)}};
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">十</span><span>시월재</span></a><nav><a href="#products">사주 상품</a><a href="#process">이용 안내</a><a href="#story">시월재 이야기</a></nav><button className="cart-button" onClick={()=>setCartOpen(true)}>장바구니 <span>{cart.length}</span></button></header>
  <section className="hero" id="top"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-copy"><p className="eyebrow">PREMIUM SAJU CURATION</p><h1>당신의 시간을 읽고,<br/><em>더 나은 내일</em>을 엽니다.</h1><p className="hero-desc">정해진 운명을 말하기보다, 타고난 기질과 삶의 흐름을 깊이 읽어 지금의 선택에 단단한 기준을 더합니다.</p><div className="hero-actions"><a className="primary" href="#products">나에게 맞는 사주 찾기</a><a className="text-link" href="#process">이용 방법 보기 →</a></div><div className="trust"><span><b>4.9</b> / 5.0 만족도</span><i/><span><b>3,200+</b> 누적 상담</span><i/><span><b>100%</b> 개별 분석</span></div></div><div className="hero-seal"><span>四柱</span><strong>運</strong><small>나의 흐름을 만나다</small></div></section>
  <section className="intro" id="story"><p className="section-label">CURATED FOR YOU</p><h2>삶의 질문에 따라<br/>섬세하게 고른 사주 리포트</h2><p>단순한 풀이를 넘어, 지금의 나에게 필요한 이해와 방향을 전합니다.</p></section>
  <section className="products-section" id="products"><div className="filter-row">{["전체","개인 운세","프리미엄","관계","자녀·양육"].map(i=><button key={i} className={category===i?"active":""} onClick={()=>setCategory(i)}>{i}</button>)}</div><div className="product-grid">{visible.map(p=><article className={`product-card ${p.recommended?"featured":""}`} key={p.id}><div className="product-art"><span className="product-tag">{p.tag}</span><b>{p.symbol}</b><small>{p.category}</small></div><div className="product-info"><p>{p.subtitle}</p><h3>{p.title}</h3><div className="price">{p.originalPrice&&<del>{money(p.originalPrice)}</del>}<strong>{money(p.price)}</strong></div><button onClick={()=>setSelected(p)}>상품 자세히 보기 <span>↗</span></button></div></article>)}</div></section>
  <section className="process" id="process"><div><p className="section-label">HOW IT WORKS</p><h2>당신만을 위한 해석이<br/>완성되는 과정</h2></div><ol>{[["01","상품 선택","지금 가장 궁금한 주제의 상품을 선택합니다."],["02","정보 입력","결제 후 생년월일시와 필요한 정보를 남겨주세요."],["03","개별 분석","전문 상담가가 사주 원국과 흐름을 직접 분석합니다."],["04","리포트 수령","3일 이내 깊이 있는 맞춤 리포트를 보내드립니다."]].map(x=><li key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]}</p></div></li>)}</ol></section>
  <section className="quote"><span>“</span><blockquote>운명은 정답이 아니라,<br/>나를 이해하는 하나의 언어입니다.</blockquote><p>시월재는 당신이 스스로의 삶을 더 잘 선택하도록 돕습니다.</p></section>
  <footer><a className="brand inverse" href="#top"><span className="brand-mark">十</span><span>시월재</span></a><p>삶의 흐름을 읽는 프리미엄 사주 큐레이션</p><div><a href="#products">상품 안내</a><a href="#process">이용 안내</a><a href="#story">브랜드 소개</a></div><small>© 2026 SIWOLJAE. All rights reserved.</small></footer>
  {selected&&<div className="overlay" onMouseDown={()=>setSelected(null)}><section className="modal detail-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="detail-symbol">{selected.symbol}</div><p className="section-label">{selected.category}</p><h2>{selected.title}</h2><p className="detail-copy">{selected.description}</p><h4>리포트 구성</h4><ul>{selected.includes.map(i=><li key={i}>✓ {i}</li>)}</ul><div className="modal-bottom"><strong>{money(selected.price)}</strong><button className="primary" onClick={()=>addCart(selected)}>장바구니 담기</button></div></section></div>}
  {cartOpen&&<div className="overlay drawer-overlay" onMouseDown={()=>setCartOpen(false)}><aside className="cart-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><h2>장바구니 <small>{cart.length}</small></h2><button className="close" onClick={()=>setCartOpen(false)}>×</button></div>{cart.length===0?<div className="empty"><b>담긴 상품이 없습니다.</b><p>지금 필요한 사주 리포트를 만나보세요.</p><button onClick={()=>setCartOpen(false)}>상품 둘러보기</button></div>:<><div className="cart-items">{cart.map(i=><div className="cart-item" key={i.id}><span>{i.symbol}</span><div><small>{i.category}</small><b>{i.title}</b><strong>{money(i.price)}</strong></div><button onClick={()=>setCart(cart.filter(p=>p.id!==i.id))}>삭제</button></div>)}</div><div className="cart-total"><span>총 결제 금액</span><strong>{money(total)}</strong></div><button className="primary checkout-button" onClick={()=>{setCartOpen(false);setCheckout(true)}}>결제하기</button></>}</aside></div>}
  {checkout&&<div className="overlay"><section className="modal checkout-modal"><button className="close" onClick={()=>setCheckout(false)}>×</button>{ordered?<div className="complete"><div>✓</div><h2>주문이 완료되었습니다</h2><p>결제 확인 후 입력하신 연락처로<br/>상담 정보 입력 링크를 보내드릴게요.</p><button className="primary" onClick={()=>{setCheckout(false);setOrdered(false);setCart([]);setCustomer({name:"",phone:"",email:""})}}>확인</button></div>:<><p className="section-label">CHECKOUT</p><h2>주문·결제</h2><div className="order-summary">{cart.map(i=><div key={i.id}><span>{i.title}</span><b>{money(i.price)}</b></div>)}<div className="order-total"><span>결제 금액</span><strong>{money(total)}</strong></div></div><label>이름<input placeholder="주문자 이름" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>연락처<input placeholder="010-0000-0000" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>이메일<input placeholder="report@example.com" type="email" value={customer.email} onChange={e=>setCustomer({...customer,email:e.target.value})}/></label><div className="pay-method"><button className="selected">신용카드</button><button>카카오페이</button><button>계좌이체</button></div>{paymentError&&<p className="payment-error">{paymentError}</p>}<button className="primary checkout-button" disabled={paying} onClick={pay}>{paying?"결제 처리 중...":`${money(total)} 결제하기`}</button><p className="demo-note">현재는 테스트 결제로 동작하며 실제 금액은 청구되지 않습니다.</p></>}</section></div>}
 </main>
}
